baseURL = 'http://leighhack.org/'
languageCode = 'en-gb'
theme = 'lhs'
title = 'Leigh Hackspace'
enableRobotsTXT = true

[sitemap]
changeFreq = 'weekly'
filename = 'sitemap.xml'
priority = -1

[imaging]
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 85
  resampleFilter = 'MitchellNetravali'

[params]
company = "Leigh Hackspace CIC"
company_number = "09404083"
copyright_years = "2023"
description = "Leigh Hackspace is a hackspace located in the north-west of England."

[params.social]
twitter = 'leigh_hackspace'

# Header links
[menu]
[[menu.main]]
name = "About"
pageRef = "about"

[[menu.main]]
name = "Facilities"
pageRef = "facilities"

[[menu.main]]
name = "Blog"
pageRef = "/blog"

[[menu.main]]
name = "Visit Us"
pageRef = "visit"

[[menu.main]]
name = "Events"
pageRef = "events"

# Social links
[[params.social_links]]
name = "mastodon"
url = "https://mastodon.social/@leigh_hackspace"
icon = "fa-mastodon"

[[params.social_links]]
name = "twitter"
url = "https://twitter.com/leigh_hackspace"
icon = "fa-twitter"

[[params.social_links]]
name = "instagram"
url = "https://www.instagram.com/leighhackspace"
icon = "fa-instagram"

[[params.social_links]]
name = "facebook"
url = "https://www.facebook.com/groups/leighhackspace/"
icon = "fa-facebook-square"

[[params.social_links]]
name = "slack"
url = "https://join.slack.com/t/leighhack/shared_invite/enQtNDYzMjEyMDMxNDExLTE1MWY5N2IwMzdhMzQ0ZWFiNDkyNzJmMGM1ZmFkODcwMGM5ODFmYmI4MjhmM2JiMWEyY2E3NTRjMTQzMzljZWU"
icon = "fa-slack"

[[params.social_links]]
name = "github"
url = "https://github.com/leigh-hackspace"
icon = "fa-github-alt"

[[params.social_links]]
name = "discourse"
url = "https://discourse.leighhack.org"
icon = "fa-discourse"
