baseURL = 'https://leighhack.org/'
languageCode = 'en-gb'
theme = 'lhs'
title = 'Leigh Hackspace'
enableRobotsTXT = true

[sitemap]
changeFreq = 'weekly'
filename = 'sitemap.xml'
priority = -1

[imaging]
bgColor = '#ffffff'
hint = 'photo'
quality = 85
resampleFilter = 'MitchellNetravali'

[params]
company = "Leigh Hackspace CIC"
company_number = "09404083"
copyright_years = "2023"
contact_email = "info@leighhack.org"
description = "Leigh Hackspace is a hackspace located in the north-west of England."
calendarUrl = "https://api.leighhack.org/events.ics"

# Header links
[menu]
[[menu.main]]
name = "About"
pageRef = "about"
weight = 1

[[menu.main]]
name = "History"
pageRef = "history"
weight = 2

[[menu.main]]
name = "Facilities"
pageRef = "facilities"
weight = 3

[[menu.main]]
name = "Blog"
pageRef = "blog"
weight = 4

[[menu.main]]
name = "Visit Us"
pageRef = "visit"
weight = 5

[[menu.main]]
name = "Events"
pageRef = "events"
weight = 6

[[menu.policies]]
name = "Code of Conduct"
pageRef = "policies/code_of_conduct"
weight = 1

[[menu.policies]]
name = "Disputes"
pageRef = "policies/disputes"
weight = 2

[[menu.policies]]
name = "CCTV Policy"
pageRef = "policies/cctv_policy"
weight = 3

# Social links
[[params.social_links]]
name = "mastodon"
url = "https://mastodon.social/@leigh_hackspace"
icon = "fab fa-mastodon"

[[params.social_links]]
name = "twitter"
url = "https://twitter.com/leigh_hackspace"
icon = "fab fa-twitter"

[[params.social_links]]
name = "instagram"
url = "https://www.instagram.com/leighhackspace"
icon = "fab fa-instagram"

[[params.social_links]]
name = "facebook"
url = "https://www.facebook.com/LeighHackspace"
icon = "fab fa-facebook-square"

[[params.social_links]]
name = "slack"
url = "https://join.slack.com/t/leighhack/shared_invite/enQtNDYzMjEyMDMxNDExLTE1MWY5N2IwMzdhMzQ0ZWFiNDkyNzJmMGM1ZmFkODcwMGM5ODFmYmI4MjhmM2JiMWEyY2E3NTRjMTQzMzljZWU"
icon = "fab fa-slack"

[[params.social_links]]
name = "github"
url = "https://github.com/leigh-hackspace"
icon = "fab fa-github-alt"

[[params.social_links]]
name = "discourse"
url = "https://discourse.leighhack.org"
icon = "fab fa-discourse"
