name = "lhs"
license = "MIT"
description = "A theme for Leigh Hackspace"
homepage = "https://leighhack.org/"
tags = []
features = []
min_version = "0.111.3"

[author]
name = "Andrew Williams"
homepage = "https://nikdoof.com"
